export const VERDICT_CONFIG = {
  'Strong fit':    { color: '#16a34a', bg: '#f0fdf4', border: '#86efac', icon: '✅' },
  'Worth a look':  { color: '#d97706', bg: '#fffbeb', border: '#fcd34d', icon: '⚠️' },
  'Probably pass': { color: '#dc2626', bg: '#fef2f2', border: '#fca5a5', icon: '❌' },
}

export const CRITERIA_LABELS = {
  beds: '3+ Beds',
  backyard: 'Fenceable Yard',
  school: 'School 7+',
  budget: '≤$750K Budget',
  yearBuilt: 'Built 2010+',
}

export const SCORE_COLOR = { '✅': '#16a34a', '⚠️': '#d97706', '❌': '#dc2626' }

export const EMPTY_FORM = {
  address: '', propertyType: 'Townhouse', price: '', beds: '', baths: '',
  sqft: '', lotSize: '', yearBuilt: '', pricePerSqft: '', dom: '',
  lastSoldPrice: '', lastSoldDate: '', propertyTaxes: '', heating: '', parking: '',
  priceHistory: '', verdict: 'Worth a look',
  criteria: { beds: '✅', backyard: '✅', school: '✅', budget: '✅', yearBuilt: '✅' },
  backyardRead: '', school: '', schoolRating: '', schoolDist: '', schoolDistance: '',
  commuteLaPetite: '', commuteBothell: '', compsRead: '', marketTrend: '',
  hoaDues: '', hoaCovers: '', hoaOwnershipType: '', hoaLayered: '',
  hoaManagement: '', hoaManagementPhone: '', hoaManagementWeb: '',
  hoaReserveStudy: '', hoaSpecialAssessments: '', hoaRentalCap: '', hoaHO6Required: '', hoaFlags: '',
  offerRangeLow: '', offerRangeHigh: '', negotiationRead: '', watchOuts: '', notes: '', dateAdded: '',
}

export const SEED_PROPERTIES = [
  {
    id: 'prop_001', dateAdded: 'Jun 28, 2026',
    address: '17116 35th Dr SE B1, Bothell, WA 98012', propertyType: 'New Construction Townhouse',
    price: '819950', beds: '3', baths: '2.5', sqft: '1611', lotSize: 'Fee-simple lot (small private)',
    yearBuilt: '2026', pricePerSqft: '509', dom: 'New — just listed',
    lastSoldPrice: 'New construction', lastSoldDate: 'N/A',
    propertyTaxes: 'TBD — estimate ~$7,500–8,500/yr', heating: 'Central A/C + forced air heat', parking: 'Attached 2-car garage',
    priceHistory: 'New construction — no price cuts yet', verdict: 'Worth a look',
    criteria: { beds: '✅', backyard: '✅', school: '✅', budget: '⚠️', yearBuilt: '✅' },
    backyardRead: 'Fee-simple lot — fencing included per builder. Small private yard. Passes hard criterion.',
    school: 'Canyon Creek Elementary', schoolRating: '10', schoolDist: 'Northshore SD', schoolDistance: '~0.8 mi',
    commuteLaPetite: '~12–15 min via I-405 N off-peak. Add 5–10 min AM peak.',
    commuteBothell: '~5–8 min to Amazon Nitro North',
    compsRead: 'Listed at $509/sqft — above area median ~$420–450/sqft. New construction premium expected.',
    marketTrend: 'Neutral-to-cooling; builders offering incentives.',
    hoaDues: 'TBD — confirm with builder', hoaCovers: 'TBD', hoaOwnershipType: 'Fee-simple — standard conventional financing',
    hoaLayered: 'Possible master HOA — confirm', hoaManagement: 'MSR Communities', hoaManagementPhone: 'TBD',
    hoaManagementWeb: 'msrcommunities.com/property/tambark15/',
    hoaReserveStudy: 'Not yet available', hoaSpecialAssessments: 'None yet', hoaRentalCap: 'TBD', hoaHO6Required: 'No — fee-simple',
    hoaFlags: '1) Get HOA dues + CC&Rs before signing.\n2) Confirm no layered master HOA.\n3) Builder warranty: 1-yr workmanship, 2-yr systems, 10-yr structural.\n4) Builder contract NOT standard NWMLS — have attorney review.',
    offerRangeLow: '790000', offerRangeHigh: '815000',
    negotiationRead: 'Builder won\'t cut list price. Push for credits: rate buydown ($8–16K), closing cost credit ($5–10K), or upgrades. Opening ask: $20–25K total credits.',
    watchOuts: '1) HOA dues unknown — confirm before offering.\n2) Builder contract not standard NWMLS.\n3) Confirm A/C is included.\n4) Ask about 2-1 ARM buydown offers.',
    notes: 'Tambark15 by MSR Communities. Strongest hard-criteria fit — fee-simple, fencing, A/C, 10/10 school. ~$70K over soft ceiling. Negotiate via credits.',
  },
  {
    id: 'prop_002', dateAdded: 'Jun 28, 2026',
    address: '13824 N Creek Dr #1702, Mill Creek, WA 98012', propertyType: 'Condo',
    price: '725000', beds: '3', baths: '2', sqft: '1500', lotSize: 'Condo — deck only',
    yearBuilt: '2004', pricePerSqft: '483', dom: '50',
    lastSoldPrice: 'Unknown', lastSoldDate: 'Unknown', propertyTaxes: '~$5,500–6,200/yr',
    heating: 'Forced air — NO central A/C', parking: '1 assigned + guest',
    priceHistory: '$769,950 → $739,950 (−$30K) → $725,000 (−$15K) — $45K total / 6% off',
    verdict: 'Probably pass',
    criteria: { beds: '✅', backyard: '❌', school: '✅', budget: '✅', yearBuilt: '⚠️' },
    backyardRead: 'FAILS hard criterion. Condo = deck-only. No private fenceable ground yard.',
    school: 'Confirm with Everett SD', schoolRating: '9', schoolDist: 'Everett SD', schoolDistance: 'TBD',
    commuteLaPetite: '~15–18 min via I-5 S off-peak. Add 10+ min AM peak.',
    commuteBothell: '~10–15 min to Amazon Nitro North',
    compsRead: 'At $483/sqft, above typical Mill Creek condo resales ($400–450/sqft). Similar 3-bed condos closed $650–700K.',
    marketTrend: 'Cooling — condos sitting longer; financing friction.',
    hoaDues: 'TBD — confirm for unit #1702', hoaCovers: 'Likely exterior, roof, water/sewer',
    hoaOwnershipType: 'CONDO — warrantability check required. HO-6 required.',
    hoaLayered: 'Nature\'s Landing master + condo sub-HOA — two sets of dues likely',
    hoaManagement: 'TBD', hoaManagementPhone: 'Get from listing agent', hoaManagementWeb: 'TBD',
    hoaReserveStudy: 'CRITICAL — 20+ yr old building. Low reserves = special-assessment risk.',
    hoaSpecialAssessments: 'Unknown — request last 5 yrs', hoaRentalCap: 'Unknown', hoaHO6Required: 'Yes — condo',
    hoaFlags: '1) Resale certificate (WA-required).\n2) Reserve study + balance — #1 doc.\n3) Special-assessment history last 5 yrs.\n4) Owner-occupancy ratio / warrantability.\n5) Confirm layered HOA total dues.',
    offerRangeLow: '685000', offerRangeHigh: '712000',
    negotiationRead: '$45K cuts + 50 DOM = strong leverage. Open at $685–690K. Settle ~$700–710K. Contingent on resale cert + reserve study.',
    watchOuts: '1) YARD IS DEALBREAKER — confirm in person.\n2) Resale certificate + reserve study.\n3) Owner-occupancy ratio.\n4) No A/C.',
    notes: 'Probably pass on hard yard criterion. Strongest negotiating position of all 7 — $45K cuts, 50 DOM.',
  },
  {
    id: 'prop_003', dateAdded: 'Jun 29, 2026',
    address: '303 202nd Pl SE, Bothell, WA 98012', propertyType: 'Townhouse (detached, Built on Lot)',
    price: '750000', beds: '4', baths: '2.5', sqft: '1683', lotSize: '3,178 sqft (0.07 ac)',
    yearBuilt: '2011', pricePerSqft: '446', dom: '46',
    lastSoldPrice: 'Unknown (held since Sep 2012)', lastSoldDate: 'Sep 2012',
    propertyTaxes: '~$6,174/yr', heating: 'Forced air gas — NO central A/C', parking: '1-car garage + 1 uncovered',
    priceHistory: '$800,000 (May 14) → $775,000 → $750,000 (Jun 26) — $50K total / 6.25% off. Vacant.',
    verdict: 'Worth a look',
    criteria: { beds: '✅', backyard: '⚠️', school: '✅', budget: '⚠️', yearBuilt: '✅' },
    backyardRead: '3,178 sqft lot, footprint ~1,350 sqft → ~1,800 sqft remaining. HOA covers front lawn only. Fencing must be confirmed in CC&Rs.',
    school: 'Crystal Springs Elementary', schoolRating: '9', schoolDist: 'Northshore SD', schoolDistance: '~1.0 mi',
    commuteLaPetite: '~15–20 min via I-5 N off-peak. AM peak adds 5–15 min.',
    commuteBothell: '~6–10 min to Amazon Nitro North — excellent',
    compsRead: 'At $446/sqft, in line with Sterling Creek complex ($430–460/sqft). Similar townhomes closed $720–770K in 2025.',
    marketTrend: 'Neutral — 98012 townhomes taking longer vs 2024.',
    hoaDues: '100', hoaCovers: 'Front lawn only. No exterior, no insurance.',
    hoaOwnershipType: 'Fee-simple BUT MLS sub-type COND — confirm with lender.',
    hoaLayered: 'No layered HOA', hoaManagement: 'Navigate Community Management',
    hoaManagementPhone: '360-512-3820', hoaManagementWeb: 'navigatecommunitymanagement.com',
    hoaReserveStudy: 'Request — 2011 buildings, 15 yrs old', hoaSpecialAssessments: 'Unknown — request from Navigate',
    hoaRentalCap: 'No rental cap confirmed', hoaHO6Required: 'No — fee-simple',
    hoaFlags: '1) LENDER FLAG — MLS sub-type COND may trigger condo underwriting. Confirm before offering.\n2) Fencing in CC&Rs — call Navigate (360-512-3820).\n3) Reserve study.\n4) 4th BR lower level — confirm legal egress.',
    offerRangeLow: '710000', offerRangeHigh: '735000',
    negotiationRead: 'Vacant + $50K cuts + 46 DOM = motivated seller. Open at $710–715K. Settle $720–735K. Include inspection contingency.',
    watchOuts: '1) MLS COND — confirm with lender first.\n2) Fencing in CC&Rs.\n3) 4th BR egress.\n4) No A/C (~$8–15K to add).',
    notes: 'Sterling Creek. Best commute combo (15–20 min La Petite + 6–10 min Bothell). Crystal Springs 9/10. Key risk: MLS COND flag.',
  },
  {
    id: 'prop_004', dateAdded: 'Jun 28, 2026',
    address: '14012 44th Dr SE Unit A, Snohomish, WA 98012', propertyType: 'Townhouse (fee-simple)',
    price: '765000', beds: '4', baths: '2.5', sqft: '1800', lotSize: 'Fee-simple lot (private fenced yard)',
    yearBuilt: '2019', pricePerSqft: '425', dom: '30',
    lastSoldPrice: '~$780K (original list)', lastSoldDate: 'Price reduction',
    propertyTaxes: '~$6,500–7,000/yr', heating: 'Forced air — confirm A/C', parking: 'Attached garage',
    priceHistory: '~$780K → $765K (~$15K cut)', verdict: 'Strong fit',
    criteria: { beds: '✅', backyard: '✅', school: '✅', budget: '⚠️', yearBuilt: '✅' },
    backyardRead: 'Private fenced yard confirmed. Fee-simple lot. Passes hard criterion. Good for a dog.',
    school: 'Silver Firs Elementary', schoolRating: '9', schoolDist: 'Snohomish SD', schoolDistance: '~1.2 mi',
    commuteLaPetite: '~20–25 min via SR-527/I-5 off-peak. AM peak adds 10+ min.',
    commuteBothell: '~12–18 min to Amazon Nitro North',
    compsRead: 'At $425/sqft, competitive for 2019 fee-simple 4-bed. Comps $400–440/sqft.',
    marketTrend: 'Neutral — 98012 longer DOM but strong fundamentals.',
    hoaDues: 'TBD — must confirm', hoaCovers: 'TBD', hoaOwnershipType: 'Fee-simple — standard financing',
    hoaLayered: 'Confirm — Manchester North may have master HOA', hoaManagement: 'TBD',
    hoaManagementPhone: 'TBD', hoaManagementWeb: 'TBD',
    hoaReserveStudy: 'Request — 2019 build', hoaSpecialAssessments: 'Unknown',
    hoaRentalCap: 'Unknown', hoaHO6Required: 'No — fee-simple',
    hoaFlags: '1) HOA dues completely unknown — get before offer.\n2) Resale certificate.\n3) Reserve study.\n4) Rental cap.\n5) Confirm A/C.',
    offerRangeLow: '730000', offerRangeHigh: '745000',
    negotiationRead: '30 DOM + $15K cut = moderate leverage. Open at $730K. Settle ~$735–745K.',
    watchOuts: '1) HOA dues unknown — critical.\n2) Confirm A/C.\n3) Confirm Silver Firs assignment with Snohomish SD.',
    notes: 'Manchester North. Best hard-criteria score of all 7. HOA dues are the one unknown. Strong fit pending confirmation.',
  },
  {
    id: 'prop_005', dateAdded: 'Jun 28, 2026',
    address: '7919 19th Dr SE, Everett, WA 98208', propertyType: 'Townhouse (fee-simple)',
    price: '600000', beds: '3', baths: '2.5', sqft: '1550', lotSize: 'Small private lot',
    yearBuilt: '2018', pricePerSqft: '387', dom: '20',
    lastSoldPrice: 'Unknown', lastSoldDate: 'Unknown', propertyTaxes: '~$5,000–5,800/yr',
    heating: 'Forced air — confirm A/C', parking: 'Attached garage', priceHistory: 'No cuts observed',
    verdict: 'Worth a look',
    criteria: { beds: '✅', backyard: '✅', school: '⚠️', budget: '✅', yearBuilt: '✅' },
    backyardRead: 'Private fenced yard confirmed. Fee-simple. Passes hard criterion.',
    school: 'View Ridge (7/10) OR Madison (3/10) — UNRESOLVED', schoolRating: '7', schoolDist: 'Everett SD', schoolDistance: 'TBD',
    commuteLaPetite: '~25–35 min via I-5 S off-peak. Longest of all evaluated.',
    commuteBothell: '~20–28 min to Amazon Nitro North',
    compsRead: 'At $387/sqft, best value of all evaluated. Similar 3-bed townhomes sold $560–620K.',
    marketTrend: 'Neutral — 98208 softer than Bothell/Mill Creek corridor.',
    hoaDues: 'TBD', hoaCovers: 'TBD', hoaOwnershipType: 'Fee-simple',
    hoaLayered: 'Unknown', hoaManagement: 'TBD', hoaManagementPhone: 'TBD', hoaManagementWeb: 'TBD',
    hoaReserveStudy: 'Request', hoaSpecialAssessments: 'Unknown', hoaRentalCap: 'Unknown', hoaHO6Required: 'No',
    hoaFlags: '1) HOA dues unknown.\n2) Resale certificate.\n3) Confirm school FIRST — make-or-break.',
    offerRangeLow: '575000', offerRangeHigh: '592000',
    negotiationRead: 'Open at $575K. Settle ~$580–592K. DO NOT write offer until school confirmed.',
    watchOuts: '1) SCHOOL IS DEALBREAKER — call Everett SD (425-385-4000) to confirm View Ridge, not Madison.\n2) Longest commute to La Petite.',
    notes: 'Alpine Heights. Best value at $600K but school unresolved. Do not pursue until View Ridge confirmed.',
  },
  {
    id: 'prop_006', dateAdded: 'Jun 28, 2026',
    address: '15800 Village Green Dr #2, Mill Creek, WA 98012', propertyType: 'Condo',
    price: '597900', beds: '2', baths: '2', sqft: '1200', lotSize: 'Condo — shared grounds',
    yearBuilt: '2004', pricePerSqft: '498', dom: '25',
    lastSoldPrice: 'Unknown', lastSoldDate: 'Unknown', propertyTaxes: '~$4,500–5,200/yr',
    heating: 'Confirm', parking: 'Assigned', priceHistory: 'No significant cuts',
    verdict: 'Probably pass',
    criteria: { beds: '❌', backyard: '⚠️', school: '⚠️', budget: '✅', yearBuilt: '⚠️' },
    backyardRead: 'Condo — shared grounds only. No private fenceable yard. Fails hard criterion.',
    school: 'TBD', schoolRating: '', schoolDist: 'Everett SD', schoolDistance: 'TBD',
    commuteLaPetite: '~15–20 min', commuteBothell: '~10–15 min',
    compsRead: 'Overpriced for a 2-bed 2004 condo at $498/sqft.', marketTrend: 'Cooling for condos in 98012.',
    hoaDues: 'TBD', hoaCovers: 'Likely exterior, roof, grounds',
    hoaOwnershipType: 'Condo — HO-6 required', hoaLayered: 'YES — MCCA master + Copper Tree sub-HOA',
    hoaManagement: 'TBD', hoaManagementPhone: 'TBD', hoaManagementWeb: 'TBD',
    hoaReserveStudy: 'Critical — 20-yr-old building', hoaSpecialAssessments: 'Unknown',
    hoaRentalCap: 'Unknown', hoaHO6Required: 'Yes',
    hoaFlags: '1) Two sets of dues (MCCA + Copper Tree).\n2) Reserve study.\n3) Resale certificate.\n4) Owner-occupancy ratio.',
    offerRangeLow: '', offerRangeHigh: '', negotiationRead: 'Not recommended — fails two hard criteria.',
    watchOuts: '1) FAILS beds (only 2).\n2) FAILS yard (condo).\n3) Dual-layer HOA dues.',
    notes: 'Copper Tree. Two hard-criteria failures. Do not pursue.',
  },
  {
    id: 'prop_007', dateAdded: 'Jun 28, 2026',
    address: '8221 53rd Ave W Unit L46, Mukilteo, WA 98275', propertyType: 'Condo (off-market)',
    price: '', beds: '2', baths: '2', sqft: '', lotSize: 'Condo — no private yard',
    yearBuilt: '', pricePerSqft: '', dom: 'Off-market',
    lastSoldPrice: 'Unknown', lastSoldDate: 'Unknown', propertyTaxes: 'Unknown',
    heating: 'Unknown', parking: 'Unknown', priceHistory: 'Off-market',
    verdict: 'Probably pass',
    criteria: { beds: '❌', backyard: '❌', school: '⚠️', budget: '⚠️', yearBuilt: '⚠️' },
    backyardRead: 'Condo — no private yard. Fails hard criterion.',
    school: 'TBD', schoolRating: '', schoolDist: 'Mukilteo SD', schoolDistance: 'TBD',
    commuteLaPetite: '~20–30 min', commuteBothell: '~25–35 min',
    compsRead: 'Off-market — no comps.', marketTrend: 'N/A',
    hoaDues: 'Unknown', hoaCovers: 'Unknown', hoaOwnershipType: 'Condo',
    hoaLayered: 'Unknown', hoaManagement: 'Unknown', hoaManagementPhone: 'Unknown', hoaManagementWeb: 'Unknown',
    hoaReserveStudy: 'Unknown', hoaSpecialAssessments: 'Unknown', hoaRentalCap: 'Unknown', hoaHO6Required: 'Yes',
    hoaFlags: 'All details unknown — off-market.',
    offerRangeLow: '', offerRangeHigh: '', negotiationRead: 'Not recommended.',
    watchOuts: '1) FAILS beds.\n2) FAILS yard.\n3) Off-market — limited data.',
    notes: 'Off-market condo. Two hard-criteria failures. Do not pursue.',
  },
]
